### ISSUE TITLE
Dodatek nie działa z najnowszą wersja joomla i virtuemart

### ISSUE THREAD

**Issue by Pminota** [dotpay/VirtueMart#2]
Przy próbie dokonania płatności pojawia się komunikat że płatność nie może zostać zrealizowana. 
W logach pojawia się błąd: 
Required Chk obtained, but hash is not equal. Obtained Chk "None" 
Required Chk obtained, but hash not equal. Obtained Chk "None", but expected Chk " ........" 
Joomla 3.9.14 oraz Virtuemart 3.6.10 10211
Testowane na różnych wersjach php od 5.6 do 7.4.
Testowane na obydwu wersjach API.
Niepoprawnie generowany klucz weryfikacyjny pomimo że wprowdzono poprawny PIN.

**Comment by sulibrat** [comment]
Dodatek do VirtueMart jest oficjalnym wydanym przez DotPay, na oficjalnym profilu DotPay w GIThubie. Sami tak piszą na swojej stronie. Jednak kiedy im się zgłasza ten błąd dostaje się odpowiedź:

> Log mówi, że oczekiwane jest przekazanie parametru "chk", który niestety nie jest dostarczany.
> Należy dodać go w Państwa integracji zgodnie z dokumentacją dostępną pod adresem https://www.dotpay.pl/developer/doc/api_payment/pl/#ochrona-integralnosci-parametrow-przekierowania-chk lub wyłączyć wymagalność przekazywania parametru "chk" przez kontakt z administracja@dotpay.pl,
> co może niestety obniżyć poziom zabezpieczeń płatności generowanych na Państwa koncie.
> 
> Pozdrawiamy
> Wsparcie Techniczne Dotpay

To nie jest nasza integracja tylko WASZA, drogie DotPay. Wprowadziliście zmianę zwiększającą bezpieczeństwo - super. Teraz wprowadźcie poprawki w swoich oficjalnych repozytoriach.

**Comment by wpawel** [comment]
Proszę o pobranie najnowszej wersji modułu: v1.0.16
