### ISSUE TITLE
Dodatek przestał działać... zupełnie

### ISSUE THREAD

**Issue by sulibrat** [dotpay/VirtueMart#3]
Joomla 3.9.24
VirtueMart 3.8.8 (10472)

Dodatek przestał zupełnie działać. Czy moglibyście w końcu dodatek zaktualizować i sprawdzić na najnowszych wersjach J! i VM???

1. Dodatek jest skonfigurowany poprawnie - działał do tej pory.
2. Przy próbie dokonania zakupu, potwierdzeniu koszyka nie następuje przekierowanie do strony dotPay.
3. Przy skonfigurowaniu by nie przekierowywać automatycznie - przycisk przejścia do strony płatności nie jest wyświetlany.

Do tego zgłaszane jest ostrzeżenie w error_log:

[19-Feb-2021 15:02:40 UTC] PHP Warning:  A non-numeric value encountered in /home/triglavs/public_html/triglav-com-pl/plugins/vmpayment/dotpay/dotpay.php on line 402
[19-Feb-2021 15:02:40 UTC] PHP Warning:  A non-numeric value encountered in /home/triglavs/public_html/triglav-com-pl/plugins/vmpayment/dotpay/dotpay.php on line 401

Pewnie nie ma związku z ogólnym błędem ale też warto by się nad tym pochylić.

Wasza dokumentacja jest do wersji 1.0.2 (no dobra, nie było zmian wymagających aktualizacji dokumentacji) a ostatnia zmiana w kodzie 26.03.2018. Już trzy lata minęły, zrobiliście zmianę dotyczącą chk a teraz dodatek się zupełnie posypał. Weźcie się wreszcie za to albo zwyczajnie przejdę do konkurencji. Może oni poważniej traktują swoje produkty. TAK, bo to jest wasz oficjalny dodatek do VM. Wypadałoby go utrzymywać.

**Comment by wpawel** [comment]
Proszę o pobranie najnowszej wersji modułu: [v1.0.16](https://github.com/dotpay/VirtueMart/releases/tag/v1.0.6)
